/**
 * Static exercise library — ~40 exercises covering all major movement patterns.
 * Add new exercises here; they become immediately available to the strain engine.
 */

import type { ExerciseLibrary, MuscleGroup } from "../recovery/types";

const LIBRARY: ExerciseLibrary[] = [
  // ─── Horizontal Push ─────────────────────────────────────────────────────────
  {
    id: "barbell_bench_press",
    name: "Barbell Bench Press",
    equipment: ["barbell", "bench"],
    movement_pattern: "horizontal_push",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delts", "triceps"],
    fatigue_factor: 0.80,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.55,
    cns_fatigue_factor: 0.50,
  },
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    equipment: ["dumbbell", "bench"],
    movement_pattern: "horizontal_push",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delts", "triceps"],
    fatigue_factor: 0.70,
    hypertrophy_weighting: 0.88,
    systemic_fatigue_factor: 0.45,
    cns_fatigue_factor: 0.40,
  },
  {
    id: "incline_barbell_press",
    name: "Incline Barbell Press",
    equipment: ["barbell", "bench"],
    movement_pattern: "horizontal_push",
    primary_muscles: ["upper_chest"],
    secondary_muscles: ["chest", "front_delts", "triceps"],
    fatigue_factor: 0.75,
    hypertrophy_weighting: 0.82,
    systemic_fatigue_factor: 0.50,
    cns_fatigue_factor: 0.45,
  },
  {
    id: "incline_dumbbell_press",
    name: "Incline Dumbbell Press",
    equipment: ["dumbbell", "bench"],
    movement_pattern: "horizontal_push",
    primary_muscles: ["upper_chest"],
    secondary_muscles: ["chest", "front_delts", "triceps"],
    fatigue_factor: 0.65,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.40,
    cns_fatigue_factor: 0.38,
  },
  {
    id: "push_up",
    name: "Push-Up",
    equipment: ["bodyweight"],
    movement_pattern: "horizontal_push",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delts", "triceps", "core"],
    fatigue_factor: 0.40,
    hypertrophy_weighting: 0.60,
    systemic_fatigue_factor: 0.25,
    cns_fatigue_factor: 0.20,
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    equipment: ["cable"],
    movement_pattern: "isolation_push",
    primary_muscles: ["chest"],
    secondary_muscles: ["front_delts"],
    fatigue_factor: 0.45,
    hypertrophy_weighting: 0.90,
    systemic_fatigue_factor: 0.20,
    cns_fatigue_factor: 0.18,
  },

  // ─── Horizontal Pull ──────────────────────────────────────────────────────────
  {
    id: "barbell_row",
    name: "Barbell Row",
    equipment: ["barbell"],
    movement_pattern: "horizontal_pull",
    primary_muscles: ["upper_back", "lats"],
    secondary_muscles: ["biceps", "rear_delts", "traps"],
    fatigue_factor: 0.80,
    hypertrophy_weighting: 0.82,
    systemic_fatigue_factor: 0.55,
    cns_fatigue_factor: 0.50,
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell Row",
    equipment: ["dumbbell"],
    movement_pattern: "horizontal_pull",
    primary_muscles: ["upper_back", "lats"],
    secondary_muscles: ["biceps", "rear_delts"],
    fatigue_factor: 0.65,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.40,
    cns_fatigue_factor: 0.38,
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    equipment: ["cable"],
    movement_pattern: "horizontal_pull",
    primary_muscles: ["upper_back"],
    secondary_muscles: ["lats", "biceps", "rear_delts"],
    fatigue_factor: 0.55,
    hypertrophy_weighting: 0.82,
    systemic_fatigue_factor: 0.32,
    cns_fatigue_factor: 0.28,
  },
  {
    id: "face_pull",
    name: "Face Pull",
    equipment: ["cable"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["rear_delts"],
    secondary_muscles: ["traps", "upper_back"],
    fatigue_factor: 0.35,
    hypertrophy_weighting: 0.75,
    systemic_fatigue_factor: 0.15,
    cns_fatigue_factor: 0.12,
  },

  // ─── Vertical Push ────────────────────────────────────────────────────────────
  {
    id: "overhead_press",
    name: "Overhead Press (Barbell)",
    equipment: ["barbell"],
    movement_pattern: "vertical_push",
    primary_muscles: ["front_delts", "side_delts"],
    secondary_muscles: ["triceps", "traps", "upper_chest"],
    fatigue_factor: 0.78,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.52,
    cns_fatigue_factor: 0.48,
  },
  {
    id: "dumbbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    equipment: ["dumbbell"],
    movement_pattern: "vertical_push",
    primary_muscles: ["front_delts", "side_delts"],
    secondary_muscles: ["triceps"],
    fatigue_factor: 0.62,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.40,
    cns_fatigue_factor: 0.38,
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    equipment: ["dumbbell", "cable"],
    movement_pattern: "isolation_push",
    primary_muscles: ["side_delts"],
    secondary_muscles: ["traps"],
    fatigue_factor: 0.30,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.12,
    cns_fatigue_factor: 0.10,
  },

  // ─── Vertical Pull ────────────────────────────────────────────────────────────
  {
    id: "pull_up",
    name: "Pull-Up",
    equipment: ["pull_up_bar"],
    movement_pattern: "vertical_pull",
    primary_muscles: ["lats"],
    secondary_muscles: ["biceps", "upper_back", "rear_delts"],
    fatigue_factor: 0.70,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.42,
    cns_fatigue_factor: 0.40,
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    equipment: ["cable"],
    movement_pattern: "vertical_pull",
    primary_muscles: ["lats"],
    secondary_muscles: ["biceps", "upper_back"],
    fatigue_factor: 0.55,
    hypertrophy_weighting: 0.83,
    systemic_fatigue_factor: 0.32,
    cns_fatigue_factor: 0.28,
  },

  // ─── Squat patterns ───────────────────────────────────────────────────────────
  {
    id: "barbell_back_squat",
    name: "Barbell Back Squat",
    equipment: ["barbell", "squat_rack"],
    movement_pattern: "squat",
    primary_muscles: ["quads", "glutes"],
    secondary_muscles: ["hamstrings", "core", "lower_back"],
    fatigue_factor: 0.95,
    hypertrophy_weighting: 0.88,
    systemic_fatigue_factor: 0.80,
    cns_fatigue_factor: 0.88,
  },
  {
    id: "front_squat",
    name: "Front Squat",
    equipment: ["barbell", "squat_rack"],
    movement_pattern: "squat",
    primary_muscles: ["quads"],
    secondary_muscles: ["glutes", "core", "upper_back"],
    fatigue_factor: 0.88,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.75,
    cns_fatigue_factor: 0.82,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    equipment: ["dumbbell", "kettlebell"],
    movement_pattern: "squat",
    primary_muscles: ["quads", "glutes"],
    secondary_muscles: ["core"],
    fatigue_factor: 0.55,
    hypertrophy_weighting: 0.72,
    systemic_fatigue_factor: 0.38,
    cns_fatigue_factor: 0.35,
  },
  {
    id: "leg_press",
    name: "Leg Press",
    equipment: ["leg_press_machine"],
    movement_pattern: "squat",
    primary_muscles: ["quads", "glutes"],
    secondary_muscles: ["hamstrings"],
    fatigue_factor: 0.72,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.45,
    cns_fatigue_factor: 0.40,
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    equipment: ["leg_extension_machine"],
    movement_pattern: "isolation_push",
    primary_muscles: ["quads"],
    secondary_muscles: [],
    fatigue_factor: 0.38,
    hypertrophy_weighting: 0.78,
    systemic_fatigue_factor: 0.18,
    cns_fatigue_factor: 0.15,
  },

  // ─── Hinge patterns ───────────────────────────────────────────────────────────
  {
    id: "conventional_deadlift",
    name: "Conventional Deadlift",
    equipment: ["barbell"],
    movement_pattern: "hinge",
    primary_muscles: ["hamstrings", "glutes", "lower_back"],
    secondary_muscles: ["quads", "traps", "forearms", "upper_back"],
    fatigue_factor: 1.00,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 1.00,
    cns_fatigue_factor: 1.00,
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    equipment: ["barbell", "dumbbell"],
    movement_pattern: "hinge",
    primary_muscles: ["hamstrings", "glutes"],
    secondary_muscles: ["lower_back", "upper_back"],
    fatigue_factor: 0.82,
    hypertrophy_weighting: 0.88,
    systemic_fatigue_factor: 0.70,
    cns_fatigue_factor: 0.72,
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    equipment: ["barbell", "bench"],
    movement_pattern: "hinge",
    primary_muscles: ["glutes"],
    secondary_muscles: ["hamstrings"],
    fatigue_factor: 0.68,
    hypertrophy_weighting: 0.92,
    systemic_fatigue_factor: 0.48,
    cns_fatigue_factor: 0.50,
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    equipment: ["leg_curl_machine"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["hamstrings"],
    secondary_muscles: [],
    fatigue_factor: 0.40,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.20,
    cns_fatigue_factor: 0.18,
  },

  // ─── Isolation — push ─────────────────────────────────────────────────────────
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    equipment: ["cable"],
    movement_pattern: "isolation_push",
    primary_muscles: ["triceps"],
    secondary_muscles: [],
    fatigue_factor: 0.28,
    hypertrophy_weighting: 0.80,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.10,
  },
  {
    id: "skull_crusher",
    name: "Skull Crusher",
    equipment: ["barbell", "dumbbell"],
    movement_pattern: "isolation_push",
    primary_muscles: ["triceps"],
    secondary_muscles: [],
    fatigue_factor: 0.35,
    hypertrophy_weighting: 0.85,
    systemic_fatigue_factor: 0.14,
    cns_fatigue_factor: 0.12,
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    equipment: ["machine", "bodyweight"],
    movement_pattern: "isolation_push",
    primary_muscles: ["calves"],
    secondary_muscles: [],
    fatigue_factor: 0.28,
    hypertrophy_weighting: 0.78,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.08,
  },

  // ─── Isolation — pull ─────────────────────────────────────────────────────────
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    equipment: ["barbell"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["biceps"],
    secondary_muscles: ["forearms"],
    fatigue_factor: 0.30,
    hypertrophy_weighting: 0.82,
    systemic_fatigue_factor: 0.12,
    cns_fatigue_factor: 0.10,
  },
  {
    id: "dumbbell_curl",
    name: "Dumbbell Curl",
    equipment: ["dumbbell"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["biceps"],
    secondary_muscles: ["forearms"],
    fatigue_factor: 0.28,
    hypertrophy_weighting: 0.82,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.09,
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    equipment: ["dumbbell"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["biceps"],
    secondary_muscles: ["forearms"],
    fatigue_factor: 0.28,
    hypertrophy_weighting: 0.78,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.09,
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    equipment: ["dumbbell", "cable"],
    movement_pattern: "isolation_pull",
    primary_muscles: ["rear_delts"],
    secondary_muscles: ["upper_back"],
    fatigue_factor: 0.28,
    hypertrophy_weighting: 0.78,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.08,
  },

  // ─── Core ─────────────────────────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    equipment: ["bodyweight"],
    movement_pattern: "core",
    primary_muscles: ["core"],
    secondary_muscles: [],
    fatigue_factor: 0.20,
    hypertrophy_weighting: 0.50,
    systemic_fatigue_factor: 0.10,
    cns_fatigue_factor: 0.08,
  },
  {
    id: "ab_rollout",
    name: "Ab Rollout",
    equipment: ["ab_wheel"],
    movement_pattern: "core",
    primary_muscles: ["core"],
    secondary_muscles: ["lats", "triceps"],
    fatigue_factor: 0.38,
    hypertrophy_weighting: 0.75,
    systemic_fatigue_factor: 0.18,
    cns_fatigue_factor: 0.15,
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    equipment: ["cable"],
    movement_pattern: "core",
    primary_muscles: ["core"],
    secondary_muscles: [],
    fatigue_factor: 0.30,
    hypertrophy_weighting: 0.78,
    systemic_fatigue_factor: 0.12,
    cns_fatigue_factor: 0.10,
  },

  // ─── Cardio ───────────────────────────────────────────────────────────────────
  {
    id: "treadmill_run",
    name: "Treadmill Run",
    equipment: ["treadmill"],
    movement_pattern: "cardio",
    primary_muscles: ["quads", "hamstrings", "calves"],
    secondary_muscles: ["glutes", "core"],
    fatigue_factor: 0.35,
    hypertrophy_weighting: 0.20,
    systemic_fatigue_factor: 0.30,
    cns_fatigue_factor: 0.15,
  },
  {
    id: "stationary_bike",
    name: "Stationary Bike",
    equipment: ["bike"],
    movement_pattern: "cardio",
    primary_muscles: ["quads", "hamstrings"],
    secondary_muscles: ["calves", "glutes"],
    fatigue_factor: 0.25,
    hypertrophy_weighting: 0.18,
    systemic_fatigue_factor: 0.22,
    cns_fatigue_factor: 0.10,
  },
];

// ─── Lookup helpers ───────────────────────────────────────────────────────────

const EXERCISE_INDEX = new Map<string, ExerciseLibrary>(
  LIBRARY.map((e) => [e.id, e])
);

export function getExercise(id: string): ExerciseLibrary | undefined {
  return EXERCISE_INDEX.get(id);
}

export function getAllExercises(): ExerciseLibrary[] {
  return LIBRARY;
}

export function getExercisesByMuscle(muscle: MuscleGroup): ExerciseLibrary[] {
  return LIBRARY.filter(
    (e) =>
      e.primary_muscles.includes(muscle) ||
      e.secondary_muscles.includes(muscle)
  );
}

export function getExercisesByPattern(
  pattern: ExerciseLibrary["movement_pattern"]
): ExerciseLibrary[] {
  return LIBRARY.filter((e) => e.movement_pattern === pattern);
}

// ─── Muscle group metadata ────────────────────────────────────────────────────

export const MUSCLE_LABELS: Record<MuscleGroup, string> = {
  chest:       "Chest",
  upper_chest: "Upper Chest",
  front_delts: "Front Delts",
  side_delts:  "Side Delts",
  rear_delts:  "Rear Delts",
  triceps:     "Triceps",
  biceps:      "Biceps",
  forearms:    "Forearms",
  upper_back:  "Upper Back",
  lats:        "Lats",
  traps:       "Traps",
  lower_back:  "Lower Back",
  core:        "Core",
  glutes:      "Glutes",
  quads:       "Quads",
  hamstrings:  "Hamstrings",
  calves:      "Calves",
};

// Dashboard-visible muscle groups (subset used in the body map)
export const BODY_MAP_MUSCLES: MuscleGroup[] = [
  "chest",
  "front_delts",
  "side_delts",
  "triceps",
  "biceps",
  "upper_back",
  "lats",
  "core",
  "glutes",
  "quads",
  "hamstrings",
  "calves",
];
